Step 10: Retrieving data using Quantmod for India stocks

```{r eval=FALSE, include=TRUE}
startIN <- as.Date("2018-07-16")
endIN <- as.Date("2018-09-16")

symbolBasketIN <- c("TATASTEEL.BO", "TECHM.BO", "BAJAJ-AUTO.BO", "ICICIBANK.BO", "LT.BO")

getSymbols(symbolBasketIN, src='yahoo', from = startIN, to = endIN)

Tata <- as.xts(`TATASTEEL.BO`)
names(Tata) <- c("Tata.Open"   ,  "Tata.High"   ,  "Tata.Low"   ,   "Tata.Close"  ,  "Tata.Volume",  "Tata.Adjusted")

Mahindra <- as.xts(`TECHM.BO`)
names(Mahindra) <- c("Mahindra.Open"   ,  "Mahindra.High"   ,  "Mahindra.Low"   ,   "Mahindra.Close"  ,  "Mahindra.Volume",  "Mahindra.Adjusted")

Bajaj <- as.xts(`BAJAJ-AUTO.BO`)
names(Bajaj) <- c("Bajaj.Open"   ,  "Bajaj.High"   ,  "Bajaj.Low"   ,   "Bajaj.Close"  ,  "Bajaj.Volume",  "Bajaj.Adjusted")

ICICI <- as.xts(`ICICIBANK.BO`)
names(ICICI) <- c("ICICI.Open"   ,  "ICICI.High"   ,  "ICICI.Low"   ,   "ICICI.Close"  ,  "ICICI.Volume",  "ICICI.Adjusted")

LT <- as.xts(`LT.BO`)
names(LT) <- c("LT.Open"   ,  "LT.High"   ,  "LT.Low"   ,   "LT.Close"  ,  "LT.Volume",  "LT.Adjusted")
```

Step 11: Calculate the return 

```{r eval=FALSE, include=TRUE}
Tata_Close <- Tata[, "Tata.Close", drop = FALSE]
Tata_Return <- (diff(Tata_Close)/Tata_Close[-length(Tata_Close)])*100
names(Tata_Return) <- c("Tata")
  
Mahindra_Close <- Mahindra[, "Mahindra.Close", drop = FALSE]
Mahindra_Return <- (diff(Mahindra_Close)/Mahindra_Close[-length(Mahindra_Close)])*100
names(Mahindra_Return) <- c("Mahindran")

Bajaj_Close <- Bajaj[, "Bajaj.Close", drop = FALSE]
Bajaj_Return <- (diff(Bajaj_Close)/Bajaj_Close[-length(Bajaj_Close)])*100
names(Bajaj_Return) <- c("Bajaj")

ICICI_Close <- ICICI[, "ICICI.Close", drop = FALSE]
ICICI_Return <- (diff(ICICI_Close)/ICICI_Close[-length(ICICI_Close)])*100
names(ICICI_Return) <- c("ICICI")

LT_Close <- LT[, "LT.Close", drop = FALSE]
LT_Return <- (diff(LT_Close)/LT_Close[-length(LT_Close)])*100
names(LT_Return) <- c("LT")
```

Step 12: Merging datasets

```{r eval=FALSE, include=TRUE}
stockPriceReturnIN<-merge(Tata_Return, Mahindra_Return, Bajaj_Return, ICICI_Return, LT_Return)

View(stockPriceReturnIN)
str(stockPriceReturnIN)
```

Step 13: List the assets and the date of the event

```{r eval=FALSE, include=TRUE}
eventDateIN<-data.frame("name"=c("Tata","Mahindra","Bajaj", "ICICI", "LT"), "when"=c("2018-08-16","2018-08-16","2018-08-16","2018-08-16","2018-08-16"))
```

Step 14: Convert the text

```{r eval=FALSE, include=TRUE}
eventDateIN$name<-as.character(eventDateIN$name)
eventDateIN$when<-as.Date(eventDateIN$when)
```

Step 15: Event Study

```{r eval=FALSE, include=TRUE}
esIN <- eventstudies::eventstudy(firm.returns = stockPriceReturnIN,
                               event.list = eventDateIN,
                               event.window = 5,
                               type = "None",
                               to.remap = TRUE,
                               remap = "cumsum",
                               inference = TRUE,
                               inference.strategy = "bootstrap",
                               )
```

Step 16: Plot event study

```{r eval=FALSE, include=TRUE}
plot(esIN)
```

Step 17: Results

```{r eval=FALSE, include=TRUE}
summary(esIN)
```



Market Model

```{r eval=FALSE, include=TRUE}
INMKT <- read.csv("IN MKT.csv")

INMKT$Return <- ((INMKT$Close-INMKT$Open)/INMKT$Open)*100

marketReturnIN<-INMKT[,c(1, 8)]
marketReturnIN <- read.zoo(marketReturnIN, drop=FALSE)
View(marketReturnIN)
str(marketReturnIN)

marketReturnIN1 <- marketReturnIN[2:41]
stockPriceReturnIN1 <- stockPriceReturnIN[2:41]
str(marketReturnIN1)
View(INMKT)
```

```{r eval=FALSE, include=TRUE}
esIN.mm <- eventstudies::eventstudy(firm.returns = stockPriceReturnIN,
                                    event.list = eventDateIN,
                                    event.window = 5,
                                    type = "marketModel",
                                    to.remap = TRUE,
                                    remap = "cumsum",
                                    inference = TRUE,
                                    inference.strategy = "bootstrap",
                                    model.args = list(market.returns=marketReturnIN1)
                                    )

                                    
```



