Step 1: Installing Packages

```{r eval=FALSE, include=TRUE}
install.packages("quantmod")
library(quantmod)
install.packages("devtools")
devtools::install_github("nipfpmf/eventstudies", ref="master")
library(dplyr)
```

Step 2: Retrieving data using Quantmod for Japanese stocks

```{r eval=FALSE, include=TRUE}
startJP <- as.Date("2018-05-28")
endJP <- as.Date("2018-07-28")

symbolBasketJP <- c("6113.T", "3865.T", "7211.T", "9735.T", "3289.T")

getSymbols(symbolBasketJP , src='yahoo', from = startJP, to = endJP)

Amada <- as.xts(`6113.T`)
names(Amada) <- c("Amada.Open"   ,  "Amada.High"   ,  "Amada.Low"   ,   "Amada.Close"  , "Amada.Volume",  "Amada.Adjusted")

Hokuetsu <- as.xts(`3865.T`)
names(Hokuetsu) <- c("Hokuetsu.Open"   ,  "Hokuetsu.High"   ,  "Hokuetsu.Low"   ,   "Hokuetsu.Close"  ,  "Hokuetsu.Volume",  "Hokuetsu.Adjusted")

Mitsubishi <- as.xts(`7211.T`)
names(Mitsubishi) <- c("Mitsubishi.Open"   ,  "Mitsubishi.High"   ,  "Mitsubishi.Low"   ,   "Mitsubishi.Close"  ,  "Mitsubishi.Volume",  "Mitsubishi.Adjusted")

Secom <- as.xts(`9735.T`)
names(Secom) <- c("Secom.Open"   ,  "Secom.High"   ,  "Secom.Low"   ,   "Secom.Close"  ,  "Secom.Volume",  "Secom.Adjusted")

Tokyu <- as.xts(`3289.T`)
names(Tokyu) <- c("Tokyu.Open"   ,  "Tokyu.High"   ,  "Tokyu.Low"   ,   "Tokyu.Close"  ,  "Tokyu.Volume",  "Tokyu.Adjusted")
```

Step 3: Calculate the return 

```{r eval=FALSE, include=TRUE}
Amada_Close <- Amada[, "Amada.Close", drop = FALSE]
Amada_Return <- (diff(Amada_Close)/Amada_Close[-length(Amada_Close)])*100
names(Amada_Return) <- c("Amada")
  
Hokuetsu_Close <- Hokuetsu[, "Hokuetsu.Close", drop = FALSE]
Hokuetsu_Return <- (diff(Hokuetsu_Close)/Hokuetsu_Close[-length(Hokuetsu_Close)])*100
names(Hokuetsu_Return) <- c("Hokuetsun")

Mitsubishi_Close <- Mitsubishi[, "Mitsubishi.Close", drop = FALSE]
Mitsubishi_Return <- (diff(Mitsubishi_Close)/Mitsubishi_Close[-length(Mitsubishi_Close)])*100
names(Mitsubishi_Return) <- c("Mitsubishi")

Secom_Close <- Secom[, "Secom.Close", drop = FALSE]
Secom_Return <- (diff(Secom_Close)/Secom_Close[-length(Secom_Close)])*100
names(Secom_Return) <- c("Secom")

Tokyu_Close <- Tokyu[, "Tokyu.Close", drop = FALSE]
Tokyu_Return <- (diff(Tokyu_Close)/Tokyu_Close[-length(Tokyu_Close)])*100
names(Tokyu_Return) <- c("Tokyu")
```

Step 4: Merging datasets

```{r eval=FALSE, include=TRUE}
stockPriceReturnJP<-merge(Amada_Return, Hokuetsu_Return, Mitsubishi_Return, Secom_Return, Tokyu_Return)

View(stockPriceReturnJP)
str(stockPriceReturnJP)
```

Step 5: List the assets and the date of the event

```{r eval=FALSE, include=TRUE}
eventDateJP<-data.frame("name"=c("Amada","Hokuetsu","Mitsubishi", "Secom", "Tokyu"), "when"=c("2018-06-28","2018-06-28","2018-06-28","2018-06-28","2018-06-28"))
```

Step 6: Convert the text

```{r eval=FALSE, include=TRUE}
eventDateJP$name<-as.character(eventDateJP$name)
eventDateJP$when<-as.Date(eventDateJP$when)
```

Step 7: Event Study

```{r eval=FALSE, include=TRUE}
esJP <- eventstudies::eventstudy(firm.returns = stockPriceReturnJP,
                               event.list = eventDateJP,
                               event.window = 5,
                               type = "None",
                               to.remap = TRUE,
                               remap = "cumsum",
                               inference = TRUE,
                               inference.strategy = "bootstrap",
                               )
```

Step 8: Plot event study

```{r eval=FALSE, include=TRUE}
plot(esJP)
```

Step 9: Results

```{r eval=FALSE, include=TRUE}
summary(esJP)
```



Market Model

```{r eval=FALSE, include=TRUE}
JPMKT <- read.csv("JP MKT.csv")

JPMKT$Return <- ((JPMKT$Close-JPMKT$Open)/JPMKT$Open)*100

marketReturnJP<-JPMKT[,c(1, 8)]
marketReturnJP <- read.zoo(marketReturnJP, drop=FALSE)
View(marketReturnJP)
str(marketReturnJP)

stockPriceReturnJP1 <- stockPriceReturnJP[2:44]
```

```{r eval=FALSE, include=TRUE}
esJP.mm <- eventstudies::eventstudy(firm.returns = stockPriceReturnJP1,
                                    event.list = eventDateJP,
                                    event.window = 5,
                                    type = "marketModel",
                                    to.remap = TRUE,
                                    remap = "cumsum",
                                    inference = TRUE,
                                    inference.strategy = "bootstrap",
                                    model.args = list(market.returns=marketReturnJP)
                                    )
```







plot(esJP.mm)

