Part 1: Installing Packages

```{r eval=FALSE, include=TRUE}
install.packages("quantmod")
library(quantmod)
install.packages("EventStudy")
library(EventStudy)
library(dplyr)
devtools::install_github("nipfpmf/eventstudies", ref="master")
```

Part 2: Retrieving data using Quantmod for Japanese stocks

```{r eval=FALSE, include=TRUE}
startJP <- as.Date("2018-05-09")
endJP <- as.Date("2018-09-09")

symbolBasketJP <- c("6113.T", "3865.T", "7211.T", "9735.T", "3289.T")

getSymbols(symbolBasketJP , src='yahoo', from = startJP, to = endJP)

Amada <- as.xts(`6113.T`)
names(Amada) <- c("Amada.Open"   ,  "Amada.High"   ,  "Amada.Low"   ,   "Amada.Close"  , "Amada.Volume",  "Amada.Adjusted")

Hokuetsu <- as.xts(`3865.T`)
names(Hokuetsu) <- c("Hokuetsu.Open"   ,  "Hokuetsu.High"   ,  "Hokuetsu.Low"   ,   "Hokuetsu.Close"  ,  "Hokuetsu.Volume",  "Hokuetsu.Adjusted")

Mitsubishi <- as.xts(`7211.T`)
names(Mitsubishi) <- c("Mitsubishi.Open"   ,  "Mitsubishi.High"   ,  "Mitsubishi.Low"   ,   "Mitsubishi.Close"  ,  "Mitsubishi.Volume",  "Mitsubishi.Adjusted")

Secom <- as.xts(`9735.T`)
names(Secom) <- c("Secom.Open"   ,  "Secom.High"   ,  "Secom.Low"   ,   "Secom.Close"  ,  "Secom.Volume",  "Secom.Adjusted")

Tokyu <- as.xts(`3289.T`)
names(Tokyu) <- c("Tokyu.Open"   ,  "Tokyu.High"   ,  "Tokyu.Low"   ,   "Tokyu.Close"  ,  "Tokyu.Volume",  "Tokyu.Adjusted")
```

Step 3: Merging datasets and extracting close price

```{r eval=FALSE, include=TRUE}
data<-merge(Amada, Hokuetsu, Mitsubishi, Secom, Tokyu)
dataJP<-data[,c(4, 10, 16, 22, 28)]
```

Step 4: Calculate the return

```{r eval=FALSE, include=TRUE}
StockPriceReturnJP <- read.csv(file="StockPriceReturnJP.csv")

dataJP$Amada.Close <- c(NA,diff(log(as.numeric(dataJP$Amada.Close)), lag=1))

dataJP$Hokuetsu.Close <- c(NA,diff(log(as.numeric(dataJP$Hokuetsu.Close)), lag=1))

dataJP$Mitsubishi.Close <- c(NA,diff(log(as.numeric(dataJP$Mitsubishi.Close)), lag=1))

dataJP$Secom.Close <- c(NA,diff(log(as.numeric(dataJP$Secom.Close)), lag=1))

dataJP$Tokyu.Close <- c(NA,diff(log(as.numeric(dataJP$Tokyu.Close)), lag=1))
```

Step 5: Convert to zoo
```{r eval=FALSE, include=TRUE}
write.zoo(StockPriceReturnJP, file="StockPriceReturnJP.csv")
?read.zoo
read.zoo(StockPriceReturnJP, format = "%Y.%m.%d")
```

Step 6: List the assets and the date of the event
```{r eval=FALSE, include=TRUE}
eventDateJP<-data.frame("name"=c("Amada","Hokuetsu","Mitsubishi", "Secom", "Tokyu"), "when"=c("2018-07-09","2018-07-09","2018-07-09","2018-07-09","2018-07-09"))
```

Step 7: Convert the text
```{r eval=FALSE, include=TRUE}
eventDateJP$name<-as.character(eventDateJP$name)
eventDateJP$when<-as.Date(eventDateJP$when)
```

Step 8: EventStudy
```{r eval=FALSE, include=TRUE}
help(EventStudy)
?EventStudy
es <- eventstudies::eventstudy(firm.returns = StockPriceReturnJP,
                               event.list = eventDateJP,
                               event.window = 7,
                               type = "None",
                               to.remap = TRUE,
                               remap = "cumsum",
                               inference = TRUE,
                               inference.strategy = "bootstrap",
                               )
```

Step 9: Plot event study 
```{r eval=FALSE, include=TRUE}
plot(esJapan) 
```

Step 10: Results
```{r eval=FALSE, include=TRUE}
summary(es.mm)
```







```{r eval=FALSE, include=TRUE}
data("SplitDates", package = "eventstudies")
SplitDates <- data.frame("name"=c("Amada","Hokuetsu","Mitsubishi", "Secom", "Tokyu"), "when"=c("2018-07-09","2018-07-09","2018-07-09","2018-07-09","2018-07-09"))
```







```{r eval=FALSE, include=TRUE}
install.packages("devtools")
devtools::install_github("EventStudyTools/api-wrapper.r")

apiUrl <- "http://api.dev.eventstudytools.com"
apiKey <- "573e58c665fcc08cc6e5a660beaad0cb"

options(apiServerUrl = apiUrl)
options(eventStudyKey = apiKey)

# initialize object
estSetup <- EventStudyAPI$new()
```


